-- RLS 回滚脚本：恢复 v9.0-rls-tighten 之前的全部政策定义
-- 生成时间：迁移应用前自动快照（pg_policies 全量导出，qual 已压平为单行）
-- 用法：在 Supabase SQL Editor 整段执行即可恢复原状
-- 说明：每个政策先 DROP IF EXISTS（无论迁移后处于何种状态）再按原定义重建，
--       因此本脚本对"已迁移"与"未迁移"两种状态均可幂等恢复。

DROP POLICY IF EXISTS "audit_logs anon read" ON public.audit_logs;
CREATE POLICY "audit_logs anon read" ON public.audit_logs AS PERMISSIVE FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "audit_logs anon write" ON public.audit_logs;
CREATE POLICY "audit_logs anon write" ON public.audit_logs AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS channel_invites_delete ON public.channel_invites;
CREATE POLICY channel_invites_delete ON public.channel_invites AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS channel_invites_insert ON public.channel_invites;
CREATE POLICY channel_invites_insert ON public.channel_invites AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS channel_invites_read ON public.channel_invites;
CREATE POLICY channel_invites_read ON public.channel_invites AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS channel_invites_update ON public.channel_invites;
CREATE POLICY channel_invites_update ON public.channel_invites AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS join_requests_delete ON public.channel_join_requests;
CREATE POLICY join_requests_delete ON public.channel_join_requests AS PERMISSIVE FOR DELETE TO authenticated USING (((app_user_id() = user_id) OR (EXISTS ( SELECT 1    FROM chat_rooms   WHERE ((chat_rooms.id = channel_join_requests.room_id) AND (chat_rooms.created_by = app_user_id())))) OR (EXISTS ( SELECT 1    FROM chat_admins   WHERE ((chat_admins.room_id = channel_join_requests.room_id) AND (chat_admins.user_id = app_user_id()))))));
DROP POLICY IF EXISTS join_requests_insert ON public.channel_join_requests;
CREATE POLICY join_requests_insert ON public.channel_join_requests AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((app_user_id() = user_id));
DROP POLICY IF EXISTS join_requests_read ON public.channel_join_requests;
CREATE POLICY join_requests_read ON public.channel_join_requests AS PERMISSIVE FOR SELECT TO public USING (((user_id = app_user_id()) OR is_room_creator(room_id, app_user_id()) OR is_room_admin(room_id, app_user_id())));
DROP POLICY IF EXISTS join_requests_update ON public.channel_join_requests;
CREATE POLICY join_requests_update ON public.channel_join_requests AS PERMISSIVE FOR UPDATE TO authenticated USING (((app_user_id() = user_id) OR (EXISTS ( SELECT 1    FROM chat_rooms   WHERE ((chat_rooms.id = channel_join_requests.room_id) AND (chat_rooms.created_by = app_user_id())))) OR (EXISTS ( SELECT 1    FROM chat_admins   WHERE ((chat_admins.room_id = channel_join_requests.room_id) AND (chat_admins.user_id = app_user_id()))))));
DROP POLICY IF EXISTS "任何人可删除入群申请" ON public.channel_join_requests;
CREATE POLICY "任何人可删除入群申请" ON public.channel_join_requests AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS "任何人可插入入群申请" ON public.channel_join_requests;
CREATE POLICY "任何人可插入入群申请" ON public.channel_join_requests AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "任何人可更新入群申请" ON public.channel_join_requests;
CREATE POLICY "任何人可更新入群申请" ON public.channel_join_requests AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS "任何人可读取入群申请" ON public.channel_join_requests;
CREATE POLICY "任何人可读取入群申请" ON public.channel_join_requests AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS channel_questionnaire_answers_delete ON public.channel_questionnaire_answers;
CREATE POLICY channel_questionnaire_answers_delete ON public.channel_questionnaire_answers AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS channel_questionnaire_answers_insert ON public.channel_questionnaire_answers;
CREATE POLICY channel_questionnaire_answers_insert ON public.channel_questionnaire_answers AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS channel_questionnaire_answers_read ON public.channel_questionnaire_answers;
CREATE POLICY channel_questionnaire_answers_read ON public.channel_questionnaire_answers AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS channel_questionnaires_delete ON public.channel_questionnaires;
CREATE POLICY channel_questionnaires_delete ON public.channel_questionnaires AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS channel_questionnaires_insert ON public.channel_questionnaires;
CREATE POLICY channel_questionnaires_insert ON public.channel_questionnaires AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS channel_questionnaires_read ON public.channel_questionnaires;
CREATE POLICY channel_questionnaires_read ON public.channel_questionnaires AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_admins_delete ON public.chat_admins;
CREATE POLICY chat_admins_delete ON public.chat_admins AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_admins_insert ON public.chat_admins;
CREATE POLICY chat_admins_insert ON public.chat_admins AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS chat_admins_read ON public.chat_admins;
CREATE POLICY chat_admins_read ON public.chat_admins AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_banned_delete ON public.chat_banned;
CREATE POLICY chat_banned_delete ON public.chat_banned AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_banned_insert ON public.chat_banned;
CREATE POLICY chat_banned_insert ON public.chat_banned AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS chat_banned_read ON public.chat_banned;
CREATE POLICY chat_banned_read ON public.chat_banned AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_channel_announcements_delete ON public.chat_channel_announcements;
CREATE POLICY chat_channel_announcements_delete ON public.chat_channel_announcements AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_channel_announcements_insert ON public.chat_channel_announcements;
CREATE POLICY chat_channel_announcements_insert ON public.chat_channel_announcements AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS chat_channel_announcements_read ON public.chat_channel_announcements;
CREATE POLICY chat_channel_announcements_read ON public.chat_channel_announcements AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_channel_announcements_update ON public.chat_channel_announcements;
CREATE POLICY chat_channel_announcements_update ON public.chat_channel_announcements AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS chat_channel_settings_delete ON public.chat_channel_settings;
CREATE POLICY chat_channel_settings_delete ON public.chat_channel_settings AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_channel_settings_insert ON public.chat_channel_settings;
CREATE POLICY chat_channel_settings_insert ON public.chat_channel_settings AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS chat_channel_settings_read ON public.chat_channel_settings;
CREATE POLICY chat_channel_settings_read ON public.chat_channel_settings AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_channel_settings_update ON public.chat_channel_settings;
CREATE POLICY chat_channel_settings_update ON public.chat_channel_settings AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS chat_channel_tools_delete ON public.chat_channel_tools;
CREATE POLICY chat_channel_tools_delete ON public.chat_channel_tools AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_channel_tools_insert ON public.chat_channel_tools;
CREATE POLICY chat_channel_tools_insert ON public.chat_channel_tools AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS chat_channel_tools_read ON public.chat_channel_tools;
CREATE POLICY chat_channel_tools_read ON public.chat_channel_tools AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_channel_tools_update ON public.chat_channel_tools;
CREATE POLICY chat_channel_tools_update ON public.chat_channel_tools AS PERMISSIVE FOR UPDATE TO authenticated USING (((EXISTS ( SELECT 1    FROM chat_rooms   WHERE ((chat_rooms.id = chat_channel_tools.room_id) AND (chat_rooms.created_by = app_user_id())))) OR (EXISTS ( SELECT 1    FROM chat_admins   WHERE ((chat_admins.room_id = chat_channel_tools.room_id) AND (chat_admins.user_id = app_user_id()))))));
DROP POLICY IF EXISTS chat_messages_delete ON public.chat_messages;
CREATE POLICY chat_messages_delete ON public.chat_messages AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_messages_insert ON public.chat_messages;
CREATE POLICY chat_messages_insert ON public.chat_messages AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS chat_messages_read ON public.chat_messages;
CREATE POLICY chat_messages_read ON public.chat_messages AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_messages_update ON public.chat_messages;
CREATE POLICY chat_messages_update ON public.chat_messages AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS chat_muted_delete ON public.chat_muted;
CREATE POLICY chat_muted_delete ON public.chat_muted AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_muted_insert ON public.chat_muted;
CREATE POLICY chat_muted_insert ON public.chat_muted AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS chat_muted_read ON public.chat_muted;
CREATE POLICY chat_muted_read ON public.chat_muted AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_muted_update ON public.chat_muted;
CREATE POLICY chat_muted_update ON public.chat_muted AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS chat_reactions_delete ON public.chat_reactions;
CREATE POLICY chat_reactions_delete ON public.chat_reactions AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_reactions_insert ON public.chat_reactions;
CREATE POLICY chat_reactions_insert ON public.chat_reactions AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS chat_reactions_read ON public.chat_reactions;
CREATE POLICY chat_reactions_read ON public.chat_reactions AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_room_members_delete ON public.chat_room_members;
CREATE POLICY chat_room_members_delete ON public.chat_room_members AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_room_members_insert ON public.chat_room_members;
CREATE POLICY chat_room_members_insert ON public.chat_room_members AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((app_user_id() = user_id) OR (EXISTS ( SELECT 1    FROM chat_rooms   WHERE ((chat_rooms.id = chat_room_members.room_id) AND (chat_rooms.created_by = app_user_id())))) OR (EXISTS ( SELECT 1    FROM chat_admins   WHERE ((chat_admins.room_id = chat_room_members.room_id) AND (chat_admins.user_id = app_user_id()))))));
DROP POLICY IF EXISTS chat_room_members_read ON public.chat_room_members;
CREATE POLICY chat_room_members_read ON public.chat_room_members AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_room_members_update ON public.chat_room_members;
CREATE POLICY chat_room_members_update ON public.chat_room_members AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS chat_rooms_delete ON public.chat_rooms;
CREATE POLICY chat_rooms_delete ON public.chat_rooms AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_rooms_insert ON public.chat_rooms;
CREATE POLICY chat_rooms_insert ON public.chat_rooms AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS chat_rooms_read ON public.chat_rooms;
CREATE POLICY chat_rooms_read ON public.chat_rooms AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_rooms_update ON public.chat_rooms;
CREATE POLICY chat_rooms_update ON public.chat_rooms AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS ctc_delete ON public.chat_tool_chains;
CREATE POLICY ctc_delete ON public.chat_tool_chains AS PERMISSIVE FOR DELETE TO authenticated USING ((app_user_id() = user_id));
DROP POLICY IF EXISTS ctc_insert ON public.chat_tool_chains;
CREATE POLICY ctc_insert ON public.chat_tool_chains AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((app_user_id() = user_id));
DROP POLICY IF EXISTS ctc_read ON public.chat_tool_chains;
CREATE POLICY ctc_read ON public.chat_tool_chains AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS ctvr_delete ON public.chat_tool_vote_records;
CREATE POLICY ctvr_delete ON public.chat_tool_vote_records AS PERMISSIVE FOR DELETE TO authenticated USING ((app_user_id() = user_id));
DROP POLICY IF EXISTS ctvr_insert ON public.chat_tool_vote_records;
CREATE POLICY ctvr_insert ON public.chat_tool_vote_records AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((app_user_id() = user_id));
DROP POLICY IF EXISTS ctvr_read ON public.chat_tool_vote_records;
CREATE POLICY ctvr_read ON public.chat_tool_vote_records AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS ctv_delete ON public.chat_tool_votes;
CREATE POLICY ctv_delete ON public.chat_tool_votes AS PERMISSIVE FOR DELETE TO authenticated USING ((app_user_id() = created_by));
DROP POLICY IF EXISTS ctv_insert ON public.chat_tool_votes;
CREATE POLICY ctv_insert ON public.chat_tool_votes AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((app_user_id() = created_by));
DROP POLICY IF EXISTS ctv_read ON public.chat_tool_votes;
CREATE POLICY ctv_read ON public.chat_tool_votes AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS ctv_update ON public.chat_tool_votes;
CREATE POLICY ctv_update ON public.chat_tool_votes AS PERMISSIVE FOR UPDATE TO authenticated USING ((app_user_id() = created_by));
DROP POLICY IF EXISTS chat_unread_delete ON public.chat_unread;
CREATE POLICY chat_unread_delete ON public.chat_unread AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS chat_unread_insert ON public.chat_unread;
CREATE POLICY chat_unread_insert ON public.chat_unread AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS chat_unread_read ON public.chat_unread;
CREATE POLICY chat_unread_read ON public.chat_unread AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS chat_unread_update ON public.chat_unread;
CREATE POLICY chat_unread_update ON public.chat_unread AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS dev_read_self ON public.developers;
CREATE POLICY dev_read_self ON public.developers AS PERMISSIVE FOR SELECT TO public USING ((app_user_id() = user_id));
DROP POLICY IF EXISTS "plugins 公开可读" ON public.plugins;
CREATE POLICY "plugins 公开可读" ON public.plugins AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS public_channels_delete ON public.public_channels;
CREATE POLICY public_channels_delete ON public.public_channels AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS public_channels_insert ON public.public_channels;
CREATE POLICY public_channels_insert ON public.public_channels AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS public_channels_read ON public.public_channels;
CREATE POLICY public_channels_read ON public.public_channels AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS public_channels_update ON public.public_channels;
CREATE POLICY public_channels_update ON public.public_channels AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS "todos anon all" ON public.todos;
CREATE POLICY "todos anon all" ON public.todos AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS user_presence_delete ON public.user_presence;
CREATE POLICY user_presence_delete ON public.user_presence AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS user_presence_insert ON public.user_presence;
CREATE POLICY user_presence_insert ON public.user_presence AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS user_presence_read ON public.user_presence;
CREATE POLICY user_presence_read ON public.user_presence AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS user_presence_update ON public.user_presence;
CREATE POLICY user_presence_update ON public.user_presence AS PERMISSIVE FOR UPDATE TO public USING (true);
